name: kamel_player
description: Kamel TV Player
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  better_player: ^0.0.83
  cupertino_icons: ^1.0.6
  wakelock_plus: ^1.2.8

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpeg
    - assets/icon.png
